# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: pod-helper
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/pod_helper/main.go
    id: pod-helper
    binary: pod-helper
    goos:
      - linux
      - windows
      - darwin
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kubectl_dsh/main.go
    id: kubectl-dsh
    binary: kubectl-dsh
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    builds:
      - pod-helper
      - kubectl-dsh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - tap:
      owner: dhenkel92
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/dhenkel92/pod-helper
    description: Kubernetes Pod Helper Util
    test: |
      system "#{bin}/pod-helper -h"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
