name: Main

on:
  pull_request:
  push:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/setup-python@v2
    - name: Install required GO libs
      run: go mod download
    - uses: pre-commit/action@v2.0.0
  build:
    runs-on: ubuntu-latest
    needs:
      - style
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build
