name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/setup-python@v2
      - name: Install required GO libs
        run: |
          go mod download
          go get github.com/fzipp/gocyclo/cmd/gocyclo
      - uses: pre-commit/action@v2.0.0
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: ./.github/scripts/test.sh
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
  build:
    runs-on: ubuntu-latest
    needs:
      - style
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build Pod Helper
        run: go build cmd/pod_helper/main.go
      - name: Build Kubectl Dsh
        run: go build cmd/kubectl_dsh/main.go
